services:
  app:
    image: "mcr.microsoft.com/devcontainers/python:1-3.12-bullseye"
    volumes:
      - ..:/workspace
    command: sleep infinity
    ports:
      - "8080:8080"
      - "5173:5173"
    depends_on:
      - db
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vault
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata: